### PR TITLE
Update checklist and add in more COPY-files

### PR DESCRIPTION
**Pull request by winston**
Bonus would be to create a script in this repo and that we can do something like:

```
\curl script | bash
```

which will copy the COPY_\* to the current folder that ran this command.

### CODE REVIEW

**Comment by JuanitoFatas** [comment]
Actually we can delete COPYME and remove all `COPY-` prefix. Then write a script to get all files to current folder?

**Comment by winston** [comment]
COPYME is still good for copying it to be pasted as an issue in a repo.

**Comment by JuanitoFatas** [comment]
The files you add in this Pull Request are templates, and this repo is Open Source Checklist. Should they live here or a new repo like Open Source Template?

**Comment by winston** [comment]
I see them as part of the checklist, so I would keep them here for now, for convenience.

**Pull request merged**
